#!/usr/bin/env python3
"""Generate docs/multilogin-api/endpoints.generated.md from spec/ archive."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "docs" / "multilogin-api" / "spec"
META = SPEC / "postman-collection-meta.json"
LAUNCHER = SPEC / "launcher-endpoints.json"
OUT = ROOT / "docs" / "multilogin-api" / "endpoints.generated.md"


def main() -> None:
    meta = json.loads(META.read_text(encoding="utf-8"))
    endpoints = json.loads(LAUNCHER.read_text(encoding="utf-8"))

    lines = [
        "# Generated endpoint index",
        "",
        "> Auto-generated by `scripts/build-api-catalog.py`. Do not edit by hand.",
        "",
        f"Source: [`spec/postman-collection-meta.json`](spec/postman-collection-meta.json)",
        f"Archived: {meta.get('archived_at', 'unknown')}",
        "",
        "## Canonical launcher endpoints",
        "",
        "| ID | Method | Path | Name |",
        "|----|--------|------|------|",
    ]
    for ep in endpoints:
        lines.append(f"| `{ep['id']}` | {ep['method']} | `{ep['path']}` | {ep['name']} |")

    lines += ["", "## API categories (full Postman collection)", ""]
    for cat in meta.get("categories", []):
        lines.append(f"- **{cat['title']}** — {cat['summary']}")

    lines += ["", "## Code sample exports", ""]
    for exp in meta.get("exports", []):
        lines.append(f"### {exp['language']} / {exp['variant']}")
        lines.append("")
        if exp.get("api_paths_extracted"):
            for p in exp["api_paths_extracted"]:
                lines.append(f"- `{p}`")
        lines.append(f"- Samples: `spec/code-samples/{exp['language']}/{exp['variant'].replace('.', '_')}/`")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
